/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 
  
  hydrologySidebar: [
    'hydrology/hydrology_hydraulics',
  //  'hydrology/technical_hyd',
  //  'hydrology/weblink_hyd',
  ],
  

 land_developmentSidebar: [
  'land_development/grading_drainage',
 ],

  sw_managmentSidebar: [
    'sw_managment/swm',
 //   'sw_managment/technical_swm',
 //   'sw_managment/weblink_swm',
 ],

  escSidebar: [
    'esc/errson_sediment',
  //  'esc/technical_esc',
  //  'esc/weblink_esc',
   ],

 fnal_servicingSidebar: [
      'fnal_servicing/functional_servicing',
 //     'fnal_servicing/technical_fsr',
 //     'fnal_servicing/weblink_fsr',
 ],

 

 floodSidebar: [
    'flood/flood_control',
//    'flood/technical_flood',
//    'flood/weblink_flood',
 ],


 rd_drainageSidebar: [
    'rd_drainage/road_drainage',
 //   'rd_drainage/technical_road',
 //   'rd_drainage/weblink_road',
 ],


shop_drawingSidebar: [
  'shop_drawing/shopdrawing_review',
],


web_linkSidebar: [
  'web_link/weblink',
],


  // permitSidebar: [
  //    'permit/permitting',
  //    'permit/technical_permit',
  //    'permit/weblink_permit',
  // ],


// sg_sdSidebar: [
 //   'sg_sd/grading_drainage',
 //   'sg_sd/technical_sd_sg',
 //   'sg_sd/weblink_sd_sg',
 //  ],



//  servicingSidebar: [
//    'servicing/site_servicing',
//    'servicing/technical_ss',
//    'servicing/weblink_ss',
//   ],








// XX03Sidebar: [
//    'XX03/000C',
// ],

// XX03Sidebar: [
//    'XX04/000D',
// ],


};

export default sidebars;
