/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 
  sw_managmentSidebar: [
    'sw_managment/swm',
    ],
  
  hydrologySidebar: [
    'hydrology/hydrology_hydraulics',
  ],
  
  sg_sdSidebar: [
    'sg_sd/grading_drainage',
   ],

  escSidebar: [
    'esc/errson_sediment',
   ],

  servicingSidebar: [
    'servicing/site_servicing',
   ],

  permitSidebar: [
      'permit/permitting',
   ],

 fnal_servicingSidebar: [
      'fnal_servicing/functional_servicing',
    ],

 floodSidebar: [
    'flood/flood_control',
 ],


// XX01Sidebar: [
//    'XX01/000A',
// ],


// XX02Sidebar: [
//    'XX01/000B',
// ],


// XX03Sidebar: [
//    'XX03/000C',
// ],

// XX03Sidebar: [
//    'XX04/000D',
// ],


};

export default sidebars;
